project:
  type: default
  title: "IPA Stata Analysis Project"

format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
    mainfont: "Times New Roman"
    include-in-header:
      - text: |
          \usepackage{booktabs}
          \usepackage{longtable}
          \usepackage{array}
          \usepackage{multirow}
          \usepackage{wrapfig}
          \usepackage{float}
          \usepackage{colortbl}
          \usepackage{pdflscape}
          \usepackage{tabu}
          \usepackage{threeparttable}
          \usepackage{dcolumn}
          \floatplacement{figure}{H}
          \floatplacement{table}{H}
    toc: true
    toc-depth: 3
    number-sections: true
    fig-pos: "H"
    tbl-pos: "H"

  typst:
    margin:
      x: 1in
      y: 1in
    fontsize: 11pt
    mainfont: "Times New Roman"
    toc: true
    number-sections: true

  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    fig-cap-location: bottom
    tbl-cap-location: top

execute:
  echo: false
  warning: false
  message: false
  cache: false

bibliography: reports/references.bib

knitr:
  opts_chunk:
    fig.align: "center"
    fig.pos: "H"
    out.width: "90%"
